name: Process and Release Squads

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  process-squads:
    name: Process Squads and Create Releases
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Squads
        run: bash scripts/download-squads.sh

      - name: Process Squads
        run: bash scripts/process-squads.sh

      - name: Create or Update Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SQUADS_UPDATED: ${{ env.SQUADS_UPDATED }}
        run: bash scripts/create-release.sh
